#!/usr/bin/env bash
# Archivist Backend Installer for Linux
# Installs the Archivist backend API and configures it as a systemd service.

set -euo pipefail

INSTALL_DIR="${1:-/opt/archivist/backend}"
PORT="${ARCHIVIST_PORT:-8000}"
SERVICE_NAME="archivist-backend"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
SOURCE_DIR="$SCRIPT_DIR/../../archivist-backend"

# --- Helpers ----------------------------------------------------------------

step()  { printf '\n\033[1;36m>>> %s\033[0m\n' "$1"; }
ok()    { printf '    \033[0;32m%s\033[0m\n' "$1"; }
warn()  { printf '    \033[0;33m%s\033[0m\n' "$1"; }
fail()  { printf '    \033[0;31m%s\033[0m\n' "$1"; exit 1; }

# --- Banner -----------------------------------------------------------------

echo ""
echo "============================================"
echo "   Archivist Backend Installer for Linux"
echo "============================================"
echo ""

# --- Prerequisites ----------------------------------------------------------

step "Checking prerequisites"

# Python 3.11+
if ! command -v python3 &>/dev/null; then
    fail "Python 3 is required. Install with: sudo apt install python3 python3-venv python3-pip"
fi

PY_VERSION=$(python3 -c 'import sys; print(f"{sys.version_info.major}.{sys.version_info.minor}")')
PY_MAJOR=$(echo "$PY_VERSION" | cut -d. -f1)
PY_MINOR=$(echo "$PY_VERSION" | cut -d. -f2)

if [ "$PY_MAJOR" -lt 3 ] || { [ "$PY_MAJOR" -eq 3 ] && [ "$PY_MINOR" -lt 11 ]; }; then
    fail "Python 3.11+ is required. Found $PY_VERSION."
fi
ok "Python $PY_VERSION"

# ODBC Driver
if ! odbcinst -q -d 2>/dev/null | grep -qi "ODBC Driver"; then
    warn "ODBC Driver 18 for SQL Server not detected."
    echo "    Install with:"
    echo "      curl https://packages.microsoft.com/keys/microsoft.asc | sudo tee /etc/apt/trusted.gpg.d/microsoft.asc"
    echo "      curl https://packages.microsoft.com/config/ubuntu/\$(lsb_release -rs)/prod.list | sudo tee /etc/apt/sources.list.d/mssql-release.list"
    echo "      sudo apt-get update && sudo ACCEPT_EULA=Y apt-get install -y msodbcsql18 unixodbc-dev"
    echo ""
    read -rp "    Continue anyway? (y/n) " answer
    if [ "$answer" != "y" ]; then exit 1; fi
else
    ok "ODBC Driver found"
fi

# --- Database Configuration ------------------------------------------------

step "Database Configuration"

read -rp "    SQL Server hostname [localhost]: " DB_SERVER
DB_SERVER="${DB_SERVER:-localhost}"

read -rp "    Database name [Archivist]: " DB_NAME
DB_NAME="${DB_NAME:-Archivist}"

read -rp "    SQL Server username [sa]: " DB_USERNAME
DB_USERNAME="${DB_USERNAME:-sa}"

read -rsp "    SQL Server password: " DB_PASSWORD
echo ""

read -rp "    ODBC driver name [ODBC Driver 18 for SQL Server]: " DB_DRIVER
DB_DRIVER="${DB_DRIVER:-ODBC Driver 18 for SQL Server}"

read -rp "    Connection encryption [Optional]: " DB_ENCRYPT
DB_ENCRYPT="${DB_ENCRYPT:-Optional}"

read -rp "    Trust server certificate [Yes]: " DB_TRUST_CERT
DB_TRUST_CERT="${DB_TRUST_CERT:-Yes}"

# Generate random JWT secret
JWT_SECRET=$(python3 -c "import secrets; print(secrets.token_urlsafe(48))")

read -rp "    Access token expiry in minutes [480]: " JWT_EXPIRY
JWT_EXPIRY="${JWT_EXPIRY:-480}"

# --- Installation -----------------------------------------------------------

step "Installing to $INSTALL_DIR"

if [ ! -d "$SOURCE_DIR" ]; then
    fail "Backend source not found at $SOURCE_DIR. Run from the repository's installers/backend/ directory."
fi

sudo mkdir -p "$INSTALL_DIR"
sudo chown "$USER:$USER" "$INSTALL_DIR"

# Copy backend files
rsync -a --exclude='.venv' --exclude='__pycache__' --exclude='*.pyc' --exclude='.env' \
    "$SOURCE_DIR/" "$INSTALL_DIR/"

ok "Backend files copied"

# Create virtual environment
step "Creating virtual environment"
VENV_DIR="$INSTALL_DIR/.venv"
if [ ! -d "$VENV_DIR" ]; then
    python3 -m venv "$VENV_DIR"
fi
ok "Virtual environment at $VENV_DIR"

# Install dependencies
step "Installing Python dependencies"
"$VENV_DIR/bin/pip" install --upgrade pip -q

if command -v poetry &>/dev/null; then
    cd "$INSTALL_DIR"
    "$VENV_DIR/bin/pip" install poetry -q
    "$VENV_DIR/bin/poetry" install --no-interaction
    cd "$SCRIPT_DIR"
else
    "$VENV_DIR/bin/pip" install \
        'fastapi[standard]' sqlalchemy pyodbc python-dateutil python-multipart \
        'passlib[bcrypt]' 'python-jose[cryptography]' python-dotenv argon2-cffi \
        pandas openpyxl python-docx docxtpl uvicorn -q
fi
ok "Dependencies installed"

# --- Generate .env ----------------------------------------------------------

step "Generating configuration"

ENV_FILE="$INSTALL_DIR/.env"
cat > "$ENV_FILE" <<EOF
# Archivist Backend Configuration
# Generated by installer on $(date '+%Y-%m-%d %H:%M:%S')

# SQL Server connection
DB_SERVER=$DB_SERVER
DB_NAME=$DB_NAME
DB_USERNAME=$DB_USERNAME
DB_PASSWORD=$DB_PASSWORD
DB_DRIVER=$DB_DRIVER
DB_ENCRYPT=$DB_ENCRYPT
DB_TRUST_CERT=$DB_TRUST_CERT

# JWT Authentication
JWT_SECRET_KEY=$JWT_SECRET
ACCESS_TOKEN_EXPIRE_MINUTES=$JWT_EXPIRY
EOF

chmod 600 "$ENV_FILE"
ok "Configuration written to $ENV_FILE"

# --- Test Connection --------------------------------------------------------

step "Testing database connection"

TEST_RESULT=$("$VENV_DIR/bin/python" -c "
import sys, os
sys.path.insert(0, '$INSTALL_DIR')
os.chdir('$INSTALL_DIR')
from dotenv import load_dotenv
load_dotenv('$ENV_FILE')
from app.database import engine
from sqlalchemy import text
try:
    with engine.connect() as c:
        c.execute(text('SELECT 1'))
    print('OK')
except Exception as e:
    print(f'FAIL: {e}')
    sys.exit(1)
" 2>&1) || true

if echo "$TEST_RESULT" | grep -q "^OK$"; then
    ok "Database connection successful"
else
    warn "Database connection test failed: $TEST_RESULT"
    echo "    You can edit $ENV_FILE and retry manually."
fi

# --- Systemd Service --------------------------------------------------------

step "Installing systemd service"

SERVICE_FILE="/etc/systemd/system/${SERVICE_NAME}.service"

sudo tee "$SERVICE_FILE" > /dev/null <<EOF
[Unit]
Description=Archivist Backend API
After=network.target

[Service]
Type=simple
User=$USER
WorkingDirectory=$INSTALL_DIR
ExecStart=$VENV_DIR/bin/uvicorn app.main:app --host 0.0.0.0 --port $PORT
Restart=always
RestartSec=5
EnvironmentFile=$ENV_FILE

[Install]
WantedBy=multi-user.target
EOF

sudo systemctl daemon-reload
sudo systemctl enable "$SERVICE_NAME"
sudo systemctl start "$SERVICE_NAME"

sleep 2
if systemctl is-active --quiet "$SERVICE_NAME"; then
    ok "Service '$SERVICE_NAME' is running"
else
    warn "Service may not have started. Check: sudo journalctl -u $SERVICE_NAME"
fi

# --- Done -------------------------------------------------------------------

echo ""
echo "============================================"
echo "   Installation Complete!"
echo "============================================"
echo ""
echo "  Install directory : $INSTALL_DIR"
echo "  Config file       : $ENV_FILE"
echo "  API port          : $PORT"
echo "  API URL           : http://localhost:$PORT"
echo "  Service name      : $SERVICE_NAME"
echo ""
echo "  Manage service:"
echo "    sudo systemctl status $SERVICE_NAME"
echo "    sudo systemctl restart $SERVICE_NAME"
echo "    sudo journalctl -u $SERVICE_NAME -f"
echo ""
echo "  API docs: http://localhost:$PORT/docs"
echo ""
